# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jdproducts',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('taskid', models.IntegerField(blank=True, null=True)),
                ('names', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=250)),
                ('field_id', models.CharField(db_column='_id', max_length=200)),
                ('reallyprice', models.CharField(db_column='reallyPrice', max_length=50)),
                ('originalprice', models.CharField(blank=True, db_column='originalPrice', max_length=50, null=True)),
                ('favourabledesc1', models.CharField(blank=True, db_column='favourableDesc1', max_length=300, null=True)),
                ('allcount', models.CharField(blank=True, db_column='AllCount', max_length=50, null=True)),
                ('goodcount', models.CharField(blank=True, db_column='GoodCount', max_length=50, null=True)),
                ('generalcount', models.CharField(blank=True, db_column='GeneralCount', max_length=50, null=True)),
                ('aftercount', models.CharField(blank=True, db_column='AfterCount', max_length=50, null=True)),
                ('poorcount', models.CharField(blank=True, db_column='PoorCount', max_length=50, null=True)),
            ],
            options={
                'db_table': 'jdproducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('taskid', models.IntegerField(blank=True, null=True)),
                ('id', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('editor', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taobaoproduct',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('taskid', models.IntegerField(blank=True, null=True)),
                ('itemid', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
                ('names', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('actualprice', models.CharField(blank=True, max_length=20, null=True)),
                ('allcount', models.CharField(blank=True, max_length=10, null=True)),
                ('goodcount', models.CharField(blank=True, max_length=10, null=True)),
                ('aftercount', models.CharField(blank=True, max_length=10, null=True)),
                ('generalcount', models.CharField(blank=True, max_length=10, null=True)),
                ('poorcount', models.CharField(blank=True, max_length=10, null=True)),
                ('sellerlink', models.CharField(blank=True, max_length=100, null=True)),
                ('sellernick', models.CharField(blank=True, db_column='sellerNick', max_length=200, null=True)),
            ],
            options={
                'db_table': 'taobaoproduct',
                'managed': False,
            },
        ),
    ]
